import { RoomMetadata } from "@/types/room";

export const MUSEUM_ROOMS: RoomMetadata[] = [
  {
    id: "do-nothing-button",
    roomNumber: 1,
    title: "Nút Chả Làm Gì",
    subtitle: "Bấm mỏi tay không có gì xảy ra",
    tagline: "Đỉnh cao của sự rảnh rỗi đương đại",
    description: "Một chiếc nút màu đỏ khổng lồ. Mỗi lần bấm chẳng mang lại bất kỳ lợi ích kinh tế nào, chỉ có bộ đếm toàn cầu tăng lên và trao cho bạn những huy hiệu vô nghĩa.",
    category: "shared-data",
    styleTheme: "brutalist",
    status: "open",
    author: "Ban Trị Sự Rảnh Rỗi",
    tags: ["Xả stress", "Bộ đếm", "Thành tựu"],
  },
  {
    id: "vague-clock",
    roomNumber: 2,
    title: "Đồng Hồ Mơ Hồ",
    subtitle: "Chỉ ước lượng, không bao giờ nói giờ chính xác",
    tagline: "Thời gian chỉ là một khái niệm tương đối",
    description: "Đồng hồ không có kim, không có số. Nó nhìn mặt trời và đoán mò bằng giọng điệu của một người lười biếng. Càng về khuya nó càng ngáp ngắn ngáp dài.",
    category: "client-only",
    styleTheme: "vintage",
    status: "open",
    author: "Hội Người Lười",
    tags: ["Thời gian", "Mơ hồ", "Triết học vỉa hè"],
  },
  {
    id: "useless-converter",
    roomNumber: 3,
    title: "Bộ Đổi Đơn Vị Vô Dụng",
    subtitle: "5 km = bao nhiêu lần bấm Enter?",
    tagline: "Mọi đơn vị đều có thể quy ra trà đá và tiếng thở dài",
    description: "Công cụ tính toán giúp bạn quy đổi độ dài, khối lượng và thời gian sang các đơn vị trời ơi đất hỡi trong đời sống lập trình viên và sinh viên.",
    category: "client-only",
    styleTheme: "win98",
    status: "open",
    author: "Viện Toán Học Vô Nghĩa",
    tags: ["Máy tính", "Quy đổi", "Hài hước"],
  },
  {
    id: "deadline-excuses",
    roomNumber: 4,
    title: "Máy Tạo Lý Do Nộp Trễ Deadline",
    subtitle: "Bình chọn lý do thuyết phục nhất",
    tagline: "Cứu rỗi đồ án và deadline vào phút chót",
    description: "Kho tàng lý do bất khả kháng được tạo ngẫu nhiên. Cộng đồng có thể bình chọn xem lý do nào nghe 'uy tín' nhất để gửi sếp hoặc giảng viên.",
    category: "shared-data",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "CLB Chạy Nước Rút",
    tags: ["Deadline", "Bình chọn", "Cứu cánh"],
  },
  {
    id: "cold-coffee",
    roomNumber: 5,
    title: "Cà Phê Nguội",
    subtitle: "Báo nhiệt độ & đếm ngược ly cà phê hết ngon",
    tagline: "Định luật Newton về làm nguội cốc cà phê văn phòng",
    description: "Nhập thời gian bạn rót cà phê, hệ thống sẽ tính toán độ nguội theo thời gian thực và cảnh báo trước khi ly cà phê biến thành nước đắng ngắt.",
    category: "client-only",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "Tín Đồ Cà Phê Phin",
    tags: ["Cà phê", "Vật lý", "Thời gian"],
  },
  {
    id: "the-only-seat",
    roomNumber: 6,
    title: "Chỗ Ngồi Duy Nhất",
    subtitle: "Một người xem, triệu người xếp hàng",
    tagline: "Trải nghiệm rạp chiếu phim cô độc nhất thế giới",
    description: "Mỗi thời điểm trên toàn cầu chỉ đúng một người được chiếm chỗ ngồi và chiêm ngưỡng nội dung bí ẩn trong 60 giây. Những người khác lịch sự đứng xếp hàng.",
    category: "realtime",
    styleTheme: "terminal",
    status: "coming-soon",
    author: "Rạp Chiếu Bóng 1 Ghế",
    tags: ["Độc quyền", "Hàng đợi", "Realtime"],
  },
  {
    id: "error-eater",
    roomNumber: 7,
    title: "Thú Cưng Ăn Lỗi",
    subtitle: "Pet ảo lớn lên nhờ ăn console.error",
    tagline: "Biến bug của bạn thành thức ăn dinh dưỡng",
    description: "Nuôi một chú quái thú pixel háu ăn. Càng nhiều lỗi Javascript văng ra, thú cưng càng béo tốt và tiến hóa.",
    category: "special",
    styleTheme: "win98",
    status: "coming-soon",
    author: "Trung Tâm Cứu Hộ Bug",
    tags: ["Extension", "Tamagotchi", "Debug"],
  },
  {
    id: "scroll-mile",
    roomNumber: 8,
    title: "Đồng Hồ Cây Số Scroll",
    subtitle: "Bạn đã cuộn chuột được bao nhiêu cây số?",
    tagline: "Đo quãng đường ngón tay bạn đã chu du trong ngày",
    description: "Đo đạc độ dài cuộn chuột thực tế trên màn hình và so sánh với độ cao cáp treo Bà Nà, đỉnh Fansipan hoặc chiều dài ngõ ngách Hà Nội.",
    category: "client-only",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "Cục Đo Lường Ngón Trỏ",
    tags: ["Cuộn chuột", "Kỷ lục", "Địa danh"],
  },
  {
    id: "git-symphony",
    roomNumber: 9,
    title: "Nhạc Từ Git History",
    subtitle: "Biến commit thành bản giao hưởng kỳ quặc",
    tagline: "Mỗi commit là một nốt nhạc của sự đau khổ",
    description: "Đọc lịch sử commit từ GitHub và chuyển đổi các mã băm SHA thành giai điệu synthesizer độc nhất vô nhị bằng Web Audio API.",
    category: "special",
    styleTheme: "y2k",
    status: "coming-soon",
    author: "Dàn Nhạc Giao Hưởng Terminal",
    tags: ["Âm nhạc", "Git", "Synth"],
  },
  {
    id: "tired-keyboard",
    roomNumber: 10,
    title: "Bàn Phím Biết Mệt",
    subtitle: "Gõ nhiều thì chữ mệt mỏi hiện chậm dần",
    tagline: "Bàn phím cũng có giới hạn chịu đựng",
    description: "Một chiếc máy đánh chữ cổ điển có thanh thể lực. Bạn gõ càng nhanh và dồn dập, phím càng mệt, chữ rơi rụng và trễ dần. Hãy dừng tay cho nó thở.",
    category: "client-only",
    styleTheme: "vintage",
    status: "open",
    author: "Hiệp Hội Bảo Vệ Bàn Phím",
    tags: ["Thể lực", "Gõ phím", "Thư giãn"],
  },
  {
    id: "idle-bonsai",
    roomNumber: 11,
    title: "Cây Lớn Khi Bạn Không Làm Gì",
    subtitle: "Động vào là héo queo ngay tức khắc",
    tagline: "Thử thách giữ bình tâm tuyệt đối",
    description: "Hạt mầm cây chỉ nảy mầm và nở hoa khi bạn không di chuột, không bấm phím và ngồi yên tĩnh lặng. Bất kỳ cử động nhỏ nào cũng làm cây rụng lá.",
    category: "client-only",
    styleTheme: "zen",
    status: "coming-soon",
    author: "Thiền Viện Lười Biếng",
    tags: ["Idle", "Zen", "Bình tâm"],
  },
  {
    id: "quang-hue-lang",
    roomNumber: 12,
    title: "Ngôn Ngữ Quảng - Huế",
    subtitle: "Răng, rứa, chừ, tê - lập trình đậm chất Trung Bộ",
    tagline: "Ngôn ngữ lập trình mang âm hưởng Cố Đô",
    description: "Trình biên dịch và sân chơi viết mã bằng phương ngữ Quảng Nam - Thừa Thiên Huế. Răng = If, Rứa = Then, Chừ = Print, Tê = Return.",
    category: "special",
    styleTheme: "terminal",
    status: "coming-soon",
    author: "Hội Lập Trình Viên Miền Trung",
    tags: ["Ngôn ngữ", "Compiler", "Địa phương"],
  },
  {
    id: "traffic-honk",
    roomNumber: 13,
    title: "Còi Xe Simulator",
    subtitle: "Chấm điểm độ mất kiên nhẫn khi kẹt xe",
    tagline: "Kèn xe vinh quang ngã tư giờ cao điểm",
    description: "Mô phỏng cảnh kẹt xe đèn đỏ. Bấm còi càng nhiệt tình và bạo lực thì điểm 'mất kiên nhẫn' càng cao. Có bảng xếp hạng hung thần đường phố.",
    category: "shared-data",
    styleTheme: "brutalist",
    status: "coming-soon",
    author: "Ban Quản Lý Giao Thông Ảo",
    tags: ["Còi xe", "Bảng xếp hạng", "Giao thông"],
  },
  {
    id: "one-word-chat",
    roomNumber: 14,
    title: "Chat Một Chữ",
    subtitle: "Mỗi người mỗi lượt chỉ được gửi đúng một từ",
    tagline: "Thiên tiểu thuyết ngẫu hứng của cộng đồng mạng",
    description: "Một cuốn sổ chung nơi mọi người cùng viết truyện. Mỗi lượt người chỉ được gõ duy nhất 1 từ rồi nhường người khác, tạo nên những câu văn cười ra nước mắt.",
    category: "realtime",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "Hội Nhà Văn Bất Đắc Dĩ",
    tags: ["Cộng đồng", "Chat", "Realtime"],
  },
  {
    id: "bug-quiz",
    roomNumber: 15,
    title: "Trắc Nghiệm: Bạn Là Loại Bug Nào?",
    subtitle: "Khám phá bản ngã lỗi lầm tiềm ẩn trong bạn",
    tagline: "Ai rồi cũng là một con bug trong vũ trụ",
    description: "5 câu hỏi trắc nghiệm tâm lý giúp tìm ra loại bug phản ánh đúng tính cách của bạn nhất: Null Pointer, Race Condition, hay Memory Leak? Kèm ảnh thẻ chia sẻ.",
    category: "client-only",
    styleTheme: "y2k",
    status: "coming-soon",
    author: "Viện Giám Định Tính Cách IT",
    tags: ["Quiz", "Thẻ căn cước", "Chia sẻ"],
  },
];
