import { RoomMetadata } from "@/types/room";

export const MUSEUM_ROOMS: RoomMetadata[] = [
  {
    id: "do-nothing-button",
    roomNumber: 1,
    title: "Nút Chả Làm Gì",
    subtitle: "Bấm nút không có gì xảy ra",
    tagline: "Đỉnh cao của sự rảnh rỗi",
    description: "Nút đỏ trơn nhẵn. Bấm vào chỉ có số đếm tăng lên.",
    category: "shared-data",
    styleTheme: "brutalist",
    status: "open",
    author: "Ban Trị Sự Rảnh Rỗi",
    tags: ["Xả stress", "Bộ đếm", "Thành tựu"],
  },
  {
    id: "vague-clock",
    roomNumber: 2,
    title: "Đồng Hồ Mơ Hồ",
    subtitle: "Hỏi nhiều thì đồng hồ cộc lốc",
    tagline: "Thời gian là khái niệm tương đối",
    description: "Đồng hồ không số. Đoán mò thời gian trong ngày.",
    category: "client-only",
    styleTheme: "vintage",
    status: "open",
    author: "Hội Người Lười",
    tags: ["Thời gian", "Mơ hồ", "Triết học vỉa hè"],
  },
  {
    id: "useless-converter",
    roomNumber: 3,
    title: "Bộ Đổi Đơn Vị Vô Dụng",
    subtitle: "Quy đổi nghiêm túc kèm sai số",
    tagline: "Mọi thứ đều quy ra tô mì Quảng",
    description: "Máy tính bỏ túi đổi đơn vị đời sống Việt Nam.",
    category: "client-only",
    styleTheme: "win98",
    status: "open",
    author: "Viện Toán Học Vô Nghĩa",
    tags: ["Máy tính", "Quy đổi", "Hài hước"],
  },
  {
    id: "deadline-excuses",
    roomNumber: 4,
    title: "Máy Tạo Lý Do Nộp Trễ Deadline",
    subtitle: "Máy in rỉ sét nhả lý do",
    tagline: "Lý do trễ hẹn in biên nhận",
    description: "Nhấn nút nhận một lý do cụt ngủn cho sếp.",
    category: "shared-data",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "CLB Chạy Nước Rút",
    tags: ["Deadline", "Bình chọn", "Cứu cánh"],
  },
  {
    id: "cold-coffee",
    roomNumber: 5,
    title: "Cà Phê Nguội",
    subtitle: "Đồ thị nguội lạnh theo thời gian",
    tagline: "Định luật Newton về cốc cà phê",
    description: "Đếm ngược thời gian ly cà phê biến thành nước đắng.",
    category: "client-only",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "Tín Đồ Cà Phê Phin",
    tags: ["Cà phê", "Vật lý", "Thời gian"],
  },
  {
    id: "the-only-seat",
    roomNumber: 6,
    title: "Chỗ Ngồi Duy Nhất",
    subtitle: "Một chỗ ngồi, xếp hàng ngắm màn hình",
    tagline: "Rạp chiếu bóng cô độc nhất thế giới",
    description: "Một người ngồi 60 giây, người khác đứng xếp hàng.",
    category: "realtime",
    styleTheme: "terminal",
    status: "coming-soon",
    author: "Rạp Chiếu Bóng 1 Ghế",
    tags: ["Độc quyền", "Hàng đợi", "Realtime"],
  },
  {
    id: "error-eater",
    roomNumber: 7,
    title: "Thú Cưng Ăn Lỗi",
    subtitle: "Tamagotchi vỗ béo bằng lỗi JS",
    tagline: "Biến stack trace thành dinh dưỡng",
    description: "Dán lỗi console cho pet ăn. Càng lỗi càng béo.",
    category: "special",
    styleTheme: "win98",
    status: "coming-soon",
    author: "Trung Tâm Cứu Hộ Bug",
    tags: ["Extension", "Tamagotchi", "Debug"],
  },
  {
    id: "scroll-mile",
    roomNumber: 8,
    title: "Đồng Hồ Cây Số Scroll",
    subtitle: "Cuộn chuột tính bằng mét cáp treo",
    tagline: "Cuộn mãi mà vẫn ngồi nguyên chỗ",
    description: "Đồng hồ công-tơ-mét đo chiều dài ngón tay cuộn.",
    category: "client-only",
    styleTheme: "vintage",
    status: "open",
    author: "Cục Đo Lường Ngón Trỏ",
    tags: ["Cuộn chuột", "Kỷ lục", "Địa danh"],
  },
  {
    id: "git-symphony",
    roomNumber: 9,
    title: "Nhạc Từ Git History",
    subtitle: "Biến commit hash thành tiếng bíp",
    tagline: "Giai điệu synthesizer từ mã băm",
    description: "Mỗi commit là một nốt nhạc Web Audio.",
    category: "special",
    styleTheme: "y2k",
    status: "coming-soon",
    author: "Dàn Nhạc Giao Hưởng Terminal",
    tags: ["Âm nhạc", "Git", "Synth"],
  },
  {
    id: "tired-keyboard",
    roomNumber: 10,
    title: "Bàn Phím Biết Mệt",
    subtitle: "Gõ nhiều thì phím xin nghỉ phép",
    tagline: "Bàn phím cũng biết biểu tình",
    description: "Máy đánh chữ có phím tự dán nhãn nghỉ phép.",
    category: "client-only",
    styleTheme: "vintage",
    status: "open",
    author: "Hiệp Hội Bảo Vệ Bàn Phím",
    tags: ["Thể lực", "Gõ phím", "Thư giãn"],
  },
  {
    id: "idle-bonsai",
    roomNumber: 11,
    title: "Cây Lớn Khi Bạn Không Làm Gì",
    subtitle: "Ngồi yên cây lớn, nhúc nhích là héo",
    tagline: "Thử thách giữ bình tâm tuyệt đối",
    description: "Không đụng chuột cây mới nở hoa.",
    category: "client-only",
    styleTheme: "zen",
    status: "open",
    author: "Thiền Viện Lười Biếng",
    tags: ["Idle", "Zen", "Bình tâm"],
  },
  {
    id: "quang-hue-lang",
    roomNumber: 12,
    title: "Ngôn Ngữ Quảng - Huế",
    subtitle: "Răng, rứa, chừ, tê lập trình",
    tagline: "Code mang âm hưởng miền Trung",
    description: "Trình thông dịch viết mã bằng phương ngữ Trung Bộ.",
    category: "special",
    styleTheme: "terminal",
    status: "coming-soon",
    author: "Hội Lập Trình Viên Miền Trung",
    tags: ["Ngôn ngữ", "Compiler", "Địa phương"],
  },
  {
    id: "traffic-honk",
    roomNumber: 13,
    title: "Còi Xe Simulator",
    subtitle: "Bấm còi đo độ mất kiên nhẫn",
    tagline: "Âm thanh ngã tư giờ cao điểm",
    description: "Bấm còi vô nghĩa khi đèn đỏ còn 45 giây.",
    category: "shared-data",
    styleTheme: "brutalist",
    status: "coming-soon",
    author: "Ban Quản Lý Giao Thông Ảo",
    tags: ["Còi xe", "Bảng xếp hạng", "Giao thông"],
  },
  {
    id: "one-word-chat",
    roomNumber: 14,
    title: "Chat Một Chữ",
    subtitle: "Mỗi người mỗi lượt đúng một từ",
    tagline: "Tiểu thuyết góp chữ cộng đồng",
    description: "Viết truyện nối từ không cần đăng nhập.",
    category: "realtime",
    styleTheme: "vintage",
    status: "coming-soon",
    author: "Hội Nhà Văn Bất Đắc Dĩ",
    tags: ["Cộng đồng", "Chat", "Realtime"],
  },
  {
    id: "bug-quiz",
    roomNumber: 15,
    title: "Trắc Nghiệm: Bạn Là Loại Bug Nào?",
    subtitle: "5 câu hỏi tìm ra bản ngã lỗi",
    tagline: "Ai rồi cũng là một con bug",
    description: "Làm quiz nhận thẻ căn cước lỗi của đời bạn.",
    category: "client-only",
    styleTheme: "y2k",
    status: "coming-soon",
    author: "Viện Giám Định Tính Cách IT",
    tags: ["Quiz", "Thẻ căn cước", "Chia sẻ"],
  },
];
